Fix failing integration test (#66)
* Fix failing integration test

A ping might not even have 'changes' array, add a check for it.

Example:

    ringpop-common/test/reaping-faulty-nodes.js:281
                && ping.body.changes[0].status !== 'alive'  // ignore old ping
                                       ^
    TypeError: Cannot read property 'status' of undefined
        at dsl.validateEventBody._.filter.status (ringpop-common/test/reaping-faulty-nodes.js:281:36)
        at baseFindIndex (ringpop-common/test/node_modules/lodash/index.js:326:11)
        at Function.findIndex (ringpop-common/test/node_modules/lodash/index.js:3261:16)
        at Array.validateEventBody [as 8] (ringpop-common/test/ringpop-assert.js:144:23)
        at progressFromCursor (ringpop-common/test/ringpop-assert.js:844:20)
        at TestCoordinator.<anonymous> (ringpop-common/test/ringpop-assert.js:861:9)
        at TestCoordinator.emit (events.js:117:20)
        at TChannelEndpointHandler.handleRequest (ringpop-common/test/fake-node.js:101:30)
        at RequestCallbackHandler.handleRequest (ringpop-common/test/node_modules/tchannel/request-handler.js:62:23)
        at TChannelEndpointHandler.handleRequest (ringpop-common/test/node_modules/tchannel/endpoint-handler.js:71:17)

* Check for array element presence instead of array

Apparently, changes can be just an empty array, and it will still match the condition

* Reaping integ test flappyness

Separate race condition in ringpop-node from the zero changelist status sent by nodeIx=0

* Another fix for the integration test

Sometimes the tombstone change can come together with an 'alive'
message. Accommodate this fact in the check.

* Improve comment wording

* Javascript style